version: "3"

### create_network,
#### docker ${remote} network create --driver overlay --attachable smartmeter
networks:
  default:
    external:
      name: smartmeter

services:

  ### create_service_nats,
  nats:
    image: logimethods/smart-meter:nats-server${postfix}
    deploy:
      placement:
        constraints:
          - node.role == manager
#      update_config:
#        parallelism: 1
#        delay: 10s
    environment:
      - READY_WHEN=\"Server is ready\"
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}
    ports:
      - "4222:4222"
      - "8222:8222"
    volumes:
      - "/proc:/writable-proc"
    command: -c gnatsd.conf -m 8222 ${NATS_DEBUG} -cluster nats://0.0.0.0:6222

  nats_cluster:
    image: logimethods/smart-meter:nats-server${postfix}
    deploy:
      mode: global
      placement:
        constraints:
          - node.role != manager
#      update_config:
#        parallelism: 1
#        delay: 10s
    environment:
      - READY_WHEN=\"Server is ready\"
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}
    volumes:
      - "/proc:/writable-proc"
    command: -c gnatsd.conf -m 8222 ${NATS_DEBUG} -cluster nats://0.0.0.0:6222 -routes nats://nats:6222

### create_service_cassandra,
### create_service_nats,
### create_service_cassandra_inject,
### create_service_app_streaming,
### create_service_prediction_trainer,
### ["create_service_telegraf_on_master", "max_voltage"],
### ["create_service_telegraf_on_master", "temperature"],
### ["create_service_telegraf_on_master", "prediction"],
### ["create_service_telegraf_on_master", "docker"],
### ["create_service_telegraf", "cassandra_write_count"],
### ["create_service_telegraf", "cassandra"],
### ["create_service", "prometheus_nats_exporter", 1],
### create_service_prediction_oracle,
### create_service_inject

volumes:
  grafana-volume:
    external: true
