services:
  ### create_service_nats,
  nats:
    environment:
      - NATS_USERNAME_FILE=/run/secrets/nats_username_secret
      - NATS_PASSWORD_FILE=/run/secrets/nats_password_secret
      - NATS_CLUSTER_USERNAME_FILE=/run/secrets/nats_cluster_username_secret
      - NATS_CLUSTER_PASSWORD_FILE=/run/secrets/nats_cluster_password_secret
    secrets:
      - nats_username_secret
      - nats_password_secret
      - nats_cluster_username_secret
      - nats_cluster_password_secret

  nats_cluster:
    environment:
      - NATS_USERNAME_FILE=/run/secrets/nats_username_secret
      - NATS_PASSWORD_FILE=/run/secrets/nats_password_secret
      - NATS_CLUSTER_USERNAME_FILE=/run/secrets/nats_cluster_username_secret
      - NATS_CLUSTER_PASSWORD_FILE=/run/secrets/nats_cluster_password_secret
    secrets:
      - nats_username_secret
      - nats_password_secret
      - nats_cluster_username_secret
      - nats_cluster_password_secret

  ## For TESTING/DEBUG ONLY! ##
  nats_client:
    environment:
      - NATS_USERNAME_FILE=/run/secrets/nats_username_secret
      - NATS_PASSWORD_FILE=/run/secrets/nats_password_secret
    secrets:
      - nats_username_secret
      - nats_password_secret

  ### create_service_cassandra_inject,
  cassandra_inject:
    environment:
      - NATS_USERNAME_FILE=/run/secrets/nats_username_secret
      - NATS_PASSWORD_FILE=/run/secrets/nats_password_secret
    secrets:
      - nats_username_secret
      - nats_password_secret

  ### create_service_app_streaming,
  app_streaming:
    environment:
      - NATS_USERNAME_FILE=/run/secrets/nats_username_secret
      - NATS_PASSWORD_FILE=/run/secrets/nats_password_secret
    secrets:
      - nats_username_secret
      - nats_password_secret

  ### create_service_prediction_trainer,
  prediction_trainer:
    environment:
      - NATS_USERNAME_FILE=/run/secrets/nats_username_secret
      - NATS_PASSWORD_FILE=/run/secrets/nats_password_secret
    secrets:
      - nats_username_secret
      - nats_password_secret

  ### ["create_service_telegraf_on_master", "max_voltage"],
  telegraf_max_voltage:
    environment:
      - NATS_USERNAME_FILE=/run/secrets/nats_username_secret
      - NATS_PASSWORD_FILE=/run/secrets/nats_password_secret
    secrets:
      - nats_username_secret
      - nats_password_secret

  ### ["create_service_telegraf_on_master", "temperature"],
  telegraf_temperature:
    environment:
      - NATS_USERNAME_FILE=/run/secrets/nats_username_secret
      - NATS_PASSWORD_FILE=/run/secrets/nats_password_secret
    secrets:
      - nats_username_secret
      - nats_password_secret

  ### create_service_inject
  inject:
    environment:
      - NATS_USERNAME_FILE=/run/secrets/nats_username_secret
      - NATS_PASSWORD_FILE=/run/secrets/nats_password_secret
    secrets:
      - nats_username_secret
      - nats_password_secret

secrets:
  nats_username_secret:
    file: ./devsecrets/nats_username_secret
  nats_password_secret:
    file: ./devsecrets/nats_password_secret
  nats_cluster_username_secret:
    file: ./devsecrets/nats_cluster_username_secret
  nats_cluster_password_secret:
    file: ./devsecrets/nats_cluster_password_secret