services:
  ### create_service_prediction_trainer,
  prediction_trainer:
    environment:
      - NATS_USERNAME_FILE=/run/secrets/nats_username_secret
      - NATS_PASSWORD_FILE=/run/secrets/nats_password_secret
    secrets:
      - nats_username_secret
      - nats_password_secret

  ### create_service_prediction_oracle,
  prediction_oracle:
    environment:
      - NATS_USERNAME_FILE=/run/secrets/nats_username_secret
      - NATS_PASSWORD_FILE=/run/secrets/nats_password_secret
    secrets:
      - nats_username_secret
      - nats_password_secret
