services:
  ### create_service_prediction_trainer,
  prediction_trainer:
    environment:
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}

  ### create_service_prediction_oracle,
  prediction_oracle:
    environment:
      - NATS_USERNAME=${NATS_USERNAME}
      - NATS_PASSWORD=${NATS_PASSWORD}
