###### JOBS #######

jobs:
- name: build-docker-app_compose
  public: ((concourse-public))
  serial: ((concourse-serial))
  serial_groups: ((concourse-compose-serial_groups))
  plan:
  - get: docker-dz_compose
    trigger: ((concourse-compose-trigger))
  - get: github-repo-app_compose
    trigger: ((concourse-compose-trigger))
  - task: complete_dockerfiles
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ((docker-dz_templater-repository))
          tag: ((docker-dz_templater-tag))((docker-additional-tag))
      inputs:
      - name: github-repo-app_compose
      outputs:
      - name: complete_dockerfiles
      run:
        path: sh
        args:
        - -exc
        - |
          cp -R github-repo-app_compose/* complete_dockerfiles/
          cd /templater/
          ./set_properties_to_templates.sh /tmp/build/*/complete_dockerfiles
  - put: docker-app_compose
    params:
      build: complete_dockerfiles/((docker-app_compose-dockerfile-path))

- name: build-docker-app_inject
  public: ((concourse-public))
  serial: ((concourse-serial))
  serial_groups: ((concourse-app-serial_groups))
  plan:
  - get: github-repo-app_inject
    trigger: ((concourse-trigger))
  - get: docker-app_compose
    trigger: ((concourse-trigger))
  - task: complete_dockerfiles
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: ((docker-app_compose-repository))
          tag: ((docker-app_compose-tag))((docker-main-tag))((docker-additional-tag))
      inputs:
      - name: github-repo-app_inject
      outputs:
      - name: complete_dockerfiles
      run:
        path: sh
        args:
        - -exc
        - |
          cp -R github-repo-app_inject/* complete_dockerfiles/
          cd /templater/
          ./set_properties_to_templates.sh /tmp/build/*/complete_dockerfiles
  - put: docker-app_inject
    params:
      build: complete_dockerfiles/((docker-app_inject-dockerfile-path))

###### RESOURCES ######

## Github Repositories ##

resources:
- name: github-repo-app_compose
  type: git
  source:
    uri: ((github-uri))
    branch: ((github-branch))
    paths:
      - ((github-app_compose-path))/**
    git_user: ((github-username))
    private_key: ((github-private-key))

- name: github-repo-app_inject
  type: git
  source:
    uri: ((github-uri))
    branch: ((github-branch))
    paths:
      - ((github-app_inject-path))/**
    git_user: ((github-username))
    private_key: ((github-private-key))

## Deetazilla Docker Images ##

- name: docker-dz_compose
  type: docker-image
  source:
#    email: ((docker-hub-email))
#    username: ((docker-hub-username))
#    password: ((docker-hub-password))
    repository: ((docker-dz_compose-repository))
    tag: ((docker-dz_compose-tag))((docker-additional-tag))

## Smart Meter Application Docker Images ##

- name: docker-app_compose
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-app_compose-repository))
    tag: ((docker-app_compose-tag))((docker-main-tag))((docker-additional-tag))

- name: docker-app_inject
  type: docker-image
  source:
    email: ((docker-hub-email))
    username: ((docker-hub-username))
    password: ((docker-hub-password))
    repository: ((docker-app_inject-repository))
    tag: ((docker-app_inject-tag))((docker-main-tag))((docker-additional-tag))

